version: "3.9"

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "dockerapp"
      - "db"
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=db;port:5433;database=universityclassroomfund;username=postgres;password=postgres"
    image: "accountingsystemofuniversityclassroomfundapi"
    networks: 
      - dockerapi-dev   
  dockerapp:
    ports:
      - "8001:80"
    image: "xodosan/accountingsystemofuniversityclassroomfundapp"
    networks: 
      - dockerapi-dev  
  db:
    image: postgres:14.1-alpine 
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "universityclassroomfund"
    ports:
      - "5433:5432"
    volumes: 
      - db_volume:/var/lib/postgresql/data
    networks: 
      - dockerapi-dev
volumes:
  db_volume: